### ISSUE TITLE
css comments incorrect

### ISSUE THREAD

**Issue by zzzeyez** [noahares/nvim-commenter#1]
it currently prefixes lines with `//` to comment them.  this is valid in some interpreters, but is not officially supported and gives errors with the cssls language server.

the correct method is to prefix with `/*` and suffix with `*/`

thank you for the plugin.  i would prefer to stick with your work than to find a new one

**Comment by noahares** [comment]
This problem is tied to another issue. Currently no form of 2-part comment string (i.e `/*comment*/` and `<!--comment-->`) is working. This is because I was lazy when making java comments work, as I just replace `/*%s*/` with `//%s`, so uncommenting is easier. This is the reason why css comments are broken. I want to fix these 2-part comment strings for a while now. Now that somebody is using the plugin I have some motivation for doing this. I will try to push it in the next couple of days.

**Comment by noahares** [comment]
@zzzeyez The changes on master should fix your problem. If everything is working, please close the issue. 
I am glad, somebody gets use out of my little plugin :)

**Comment by zzzeyez** [comment]
works!  thanks lots
